on:
  push:
     branches:
       - sources


name: ðŸš€ Build and Deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup R version-stable R 4.0.2
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.2'
       
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install rmarkdown, blogdown # might need knitr
        run: Rscript -e 'install.packages(c("rmarkdown","blogdown"))'
       
      - name: Install hugo
        run: Rscript -e 'blogdown::install_hugo()'
 
      - name: Build site with blogdown
        run: Rscript -e "blogdown::build_site()"
 
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.

  
# site is built on sources branch, deploy on master branch
